from importlib import metadata

__version__ = metadata.version(__package__)

from ._typing import Annotated
from .dataclass import (
    DataclassStructProtocol,
    dataclass_struct,
    get_struct_size,
    is_dataclass_struct,
)
from .field import (
    BoolField,
    CharField,
    Float32Field,
    Float64Field,
    IntField,
    NativeIntField,
    PointerField,
    SignedStdIntField,
    SizeField,
    StdIntField,
    UnsignedStdIntField,
)
from .types import (
    F32,
    F64,
    I8,
    I16,
    I32,
    I64,
    U8,
    U16,
    U32,
    U64,
    Bool,
    Char,
    Int,
    Long,
    LongLong,
    PadAfter,
    PadBefore,
    Pointer,
    Short,
    SignedChar,
    SignedSize,
    UnsignedChar,
    UnsignedInt,
    UnsignedLong,
    UnsignedLongLong,
    UnsignedShort,
    UnsignedSize,
)

__all__ = (
    'Annotated',
    'Bool',
    'BoolField',
    'Char',
    'CharField',
    'dataclass_struct',
    'DataclassStructProtocol',
    'F32',
    'F64',
    'Float32Field',
    'Float64Field',
    'get_struct_size',
    'I16',
    'I32',
    'I64',
    'I8',
    'Int',
    'IntField',
    'is_dataclass_struct',
    'Long',
    'LongLong',
    'NativeIntField',
    'PadAfter',
    'PadBefore',
    'Pointer',
    'PointerField',
    'Short',
    'SignedChar',
    'SignedSize',
    'SignedStdIntField',
    'SizeField',
    'StdIntField',
    'U16',
    'U32',
    'U64',
    'U8',
    'UnsignedChar',
    'UnsignedInt',
    'UnsignedLong',
    'UnsignedLongLong',
    'UnsignedShort',
    'UnsignedSize',
    'UnsignedStdIntField',
)
