name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  UV_VERSION: "0.11.7"

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_HOME: /home/runner/.pre-commit-cache
      PRE_COMMIT_VERSION: "4.5.1"
      PYTHON_VERSION: "3.14"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: "true"
      - name: Configure pre-commit cache
        uses: actions/cache@v5
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: pre-commit-${{ runner.os }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - name: Run pre-commit hooks
        run: uvx "pre-commit==$PRE_COMMIT_VERSION" run --all-files --show-diff-on-failure --color=always

  tests:
    needs: pre-commit-checks
    strategy:
      matrix:
        pyversion: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        os: ["Ubuntu", "Windows", "macOS"]
        include:
          - os: Windows
            image: windows-latest
          - os: Ubuntu
            image: ubuntu-latest
          - os: macOS
            image: macos-latest
    name: ${{ matrix.os }} / ${{ matrix.pyversion }}
    runs-on: ${{ matrix.image }}
    defaults:
      run:
        shell: bash
    env:
      UV_LOCKED: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.pyversion }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.pyversion }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync

      - name: Python type checking
        run: uv run mypy .

      - name: Configure MSVC
        if: matrix.os == 'Windows'
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          set >> "%GITHUB_ENV%"

      - name: Run tests
        run: COLUMNS=120 uv run pytest --color=yes --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        if: matrix.os == 'Ubuntu' && matrix.pyversion == '3.13'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

  build-docs:
    needs: tests
    runs-on: ubuntu-latest
    env:
      SITE_DIR: site/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          cache-dependency-glob: requirements-docs.txt
          activate-environment: true
      - name: Install Python dependencies
        run: uv pip install -r requirements-docs.txt
      - name: Configure mkdocs for GitHub Pages
        run: |
          sed -i 's,^site_url: .*$,site_url: https://harrymander.xyz/dataclasses-struct/,' mkdocs.yml
          ! git diff --color=always --exit-code -- mkdocs.yml
      - name: Build site
        run: mkdocs build --strict --site-dir "$SITE_DIR"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        id: deployment
        with:
          path: ${{ env.SITE_DIR }}

  publish-docs:
    if: "${{ github.ref == 'refs/heads/main' }}"
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      # The current branch must have access to the github-pages environment.
      # See 'Deployment branches and tags' settings for 'github-pages'
      # environment in
      # github.com/harrymander/dataclasses-struct/settings/environments
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
